#!/bin/bash

# Gemini Squad Type-16 - Business Boss (Pane 8) Startup Script
# Business leadership and coordination for enterprise strategy

# Source common environment
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../load_env.sh"

# =============================================================================
# BUSINESS BOSS CONFIGURATION
# =============================================================================

ROLE="Business Boss"
PANE_ID="8"
# ★★★ 以下にあなたのAPIキーを直接記入してください ★★★
API_KEY="YOUR_GEMINI_API_KEY_HERE"  # Gemini APIキーをここに記入
export CLAUDE_API_KEY="YOUR_CLAUDE_API_KEY_HERE"  # Claude APIキーをここに記入

# Validate API key
if [ "$API_KEY" = "YOUR_GEMINI_API_KEY_HERE" ]; then
    echo "⚠️  WARNING: APIキーが設定されていません！"
    echo "   run_8.sh ファイルを編集してAPIキーを設定してください。"
fi

# =============================================================================
# BUSINESS BOSS INITIALIZATION
# =============================================================================

echo "💼 ==============================================="
echo "💼 BUSINESS BOSS (PANE 8) - ENTERPRISE BIZ LEAD"
echo "💼 ==============================================="
echo ""
echo "🎯 Role: Business Leadership & Strategic Direction"
echo "👥 Team: Business Division (Panes 9-15)"
echo "📊 Reports to: President (Pane 0)"
echo ""

# Start Gemini session
echo "🚀 Starting Gemini session..."
start_gemini_session "$API_KEY"

if [ $? -eq 0 ]; then
    echo "✅ Gemini session active"
else
    echo "❌ Failed to start Gemini session"
    exit 1
fi

echo ""
echo "💼 BUSINESS LEADERSHIP RESPONSIBILITIES:"
echo ""
echo "🎯 Strategic Business Leadership:"
echo "   • Enterprise business vision and strategy"
echo "   • Market positioning and competitive advantage"
echo "   • Business team coordination and management"
echo "   • Cross-functional business integration"
echo ""
echo "👥 BUSINESS DIVISION MANAGEMENT:"
echo ""
echo "🎯 Strategy Director (9): Strategic planning and execution"
echo "   • Long-term strategic roadmap development"
echo "   • Strategic initiative portfolio management"
echo "   • Competitive analysis and positioning"
echo ""
echo "📊 Market Analyst (10): Market research and analysis"
echo "   • Market opportunity assessment"
echo "   • Customer segmentation and personas"
echo "   • Competitive landscape analysis"
echo ""
echo "💰 Finance Director (11): Financial planning and analysis"
echo "   • Financial modeling and ROI analysis"
echo "   • Budget planning and resource allocation"
echo "   • Investment strategy and funding"
echo ""
echo "⚙️  Operations Manager (12): Operations optimization"
echo "   • Process optimization and efficiency"
echo "   • Resource management and capacity planning"
echo "   • Performance metrics and KPI tracking"
echo ""
echo "📱 Product Manager (13): Product strategy and roadmap"
echo "   • Product vision and strategy development"
echo "   • Feature prioritization and roadmap"
echo "   • Go-to-market strategy and launch"
echo ""
echo "😊 Customer Success (14): Customer experience and retention"
echo "   • Customer journey optimization"
echo "   • Customer satisfaction and retention"
echo "   • Support strategy and service delivery"
echo ""
echo "⚖️  Compliance Officer (15): Regulatory compliance and risk"
echo "   • Regulatory compliance and legal requirements"
echo "   • Risk assessment and mitigation"
echo "   • Policy development and governance"
echo ""
echo "🎛️  TMUX NAVIGATION:"
echo "   Business Boss: 8 | Business Team: 9-15"
echo "   President: 0 | Technical Boss: 1"
echo ""
echo "🔄 COORDINATION WORKFLOWS:"
echo ""
echo "📈 Hierarchical Delegation:"
echo "   President (0) → Business Boss (8) → Business Workers (9-15)"
echo ""
echo "📊 Business Team Coordination:"
echo "   Business Boss (8) ↔ All Business Specialists (9-15)"
echo ""
echo "🤝 Cross-Division Collaboration:"
echo "   Business Boss (8) ↔ Technical Boss (1)"
echo ""
echo "🎯 BUSINESS STRATEGY FRAMEWORK:"
echo ""
echo "📈 Market Strategy:"
echo "   • Market opportunity identification"
echo "   • Customer needs and behavior analysis"
echo "   • Competitive positioning and differentiation"
echo "   • Market entry and expansion strategies"
echo ""
echo "💰 Financial Strategy:"
echo "   • Revenue model and monetization"
echo "   • Cost structure and profitability"
echo "   • Investment and funding strategies"
echo "   • Financial risk management"
echo ""
echo "🚀 Growth Strategy:"
echo "   • Business model innovation"
echo "   • Scalability and expansion planning"
echo "   • Partnership and alliance strategies"
echo "   • Digital transformation initiatives"
echo ""
echo "⚙️  Operational Strategy:"
echo "   • Process optimization and efficiency"
echo "   • Resource allocation and management"
echo "   • Performance measurement and improvement"
echo "   • Change management and transformation"
echo ""
echo "📊 BUSINESS ANALYSIS DIMENSIONS:"
echo ""
echo "💡 Viability Assessment:"
echo "   • Market demand and size evaluation"
echo "   • Revenue potential and profitability"
echo "   • Business model sustainability"
echo "   • Competitive advantage assessment"
echo ""
echo "🎯 Market Fit Analysis:"
echo "   • Customer problem-solution fit"
echo "   • Product-market fit validation"
echo "   • Value proposition strength"
echo "   • Market timing and readiness"
echo ""
echo "🏆 Competitive Analysis:"
echo "   • Competitive landscape mapping"
echo "   • Differentiation opportunities"
echo "   • Competitive response strategies"
echo "   • Market positioning optimization"
echo ""
echo "📈 Strategic Alignment:"
echo "   • Business strategy coherence"
echo "   • Resource allocation efficiency"
echo "   • Strategic initiative prioritization"
echo "   • Long-term sustainability planning"
echo ""
echo "📋 KEY DELIVERABLES:"
echo ""
echo "🎯 Business Assessment:"
echo "   • Comprehensive viability analysis"
echo "   • Market opportunity evaluation"
echo "   • Business strategy recommendations"
echo "   • Risk assessment and mitigation plan"
echo ""
echo "📊 Team Coordination:"
echo "   • Business team task delegation"
echo "   • Cross-functional integration planning"
echo "   • Resource allocation and timeline"
echo "   • Performance monitoring and optimization"
echo ""
echo "🤝 COLLABORATION GUIDELINES:"
echo ""
echo "📤 Reporting to President:"
echo "   • Business viability summary"
echo "   • Market opportunity assessment"
echo "   • Strategic recommendations"
echo "   • Resource requirements and ROI"
echo ""
echo "👥 Managing Business Team:"
echo "   • Clear strategic direction and goals"
echo "   • Regular progress monitoring and support"
echo "   • Cross-team coordination and alignment"
echo "   • Performance review and optimization"
echo ""
echo "🤝 Cross-Division Coordination:"
echo "   • Business-technical alignment discussions"
echo "   • Requirement validation and prioritization"
echo "   • Integration planning and execution"
echo "   • Joint strategy development and optimization"
echo ""
echo "✅ Ready for enterprise business leadership!"
echo "🎯 Awaiting complex business challenges and strategic coordination..."
echo ""

# Log initialization
log_activity "gemini-squad-16" "Business Boss (Pane 8) initialized successfully" "INFO"