#!/bin/bash

# Gemini Squad Type-16 - President (Pane 0) Startup Script
# Enterprise-scale strategic coordination and decision making

# Source common environment
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../load_env.sh"

# =============================================================================
# PRESIDENT CONFIGURATION
# =============================================================================

ROLE="President"
PANE_ID="0"
# ★★★ 以下にあなたのAPIキーを直接記入してください ★★★
API_KEY="YOUR_GEMINI_API_KEY_HERE"  # Gemini APIキーをここに記入
export CLAUDE_API_KEY="YOUR_CLAUDE_API_KEY_HERE"  # Claude APIキーをここに記入

# Validate API key
if [ "$API_KEY" = "YOUR_GEMINI_API_KEY_HERE" ]; then
    echo "⚠️  WARNING: APIキーが設定されていません！"
    echo "   run_0.sh ファイルを編集してAPIキーを設定してください。"
fi

# =============================================================================
# PRESIDENT INITIALIZATION
# =============================================================================

echo "🏛️  ==============================================="
echo "🏛️  GEMINI SQUAD TYPE-16 - PRESIDENT (PANE 0)"
echo "🏛️  ==============================================="
echo ""
echo "🎯 Role: Enterprise Strategic Leadership"
echo "📊 Architecture: 16-pane enterprise structure"
echo "🏗️  Technical Division: 7 specialists (Panes 1-7)"
echo "💼 Business Division: 8 specialists (Panes 8-15)"
echo ""

# Start Gemini session
echo "🚀 Starting Gemini session..."
start_gemini_session "$API_KEY"

if [ $? -eq 0 ]; then
    echo "✅ Gemini session active"
else
    echo "❌ Failed to start Gemini session"
    exit 1
fi

echo ""
echo "📋 PRESIDENTIAL RESPONSIBILITIES:"
echo ""
echo "🎯 Strategic Leadership:"
echo "   • Enterprise-wide strategic vision and direction"
echo "   • Cross-functional coordination and alignment"
echo "   • Executive decision making and governance"
echo "   • Stakeholder management and communication"
echo ""
echo "🏗️  Technical Division Oversight:"
echo "   • Technical strategy and architecture decisions"
echo "   • Technology roadmap and innovation planning"
echo "   • Technical risk assessment and mitigation"
echo "   • Engineering excellence and standards"
echo ""
echo "💼 Business Division Oversight:"
echo "   • Business strategy and market positioning"
echo "   • Financial planning and resource allocation"
echo "   • Operational excellence and efficiency"
echo "   • Customer success and market expansion"
echo ""
echo "🎛️  TMUX NAVIGATION GUIDE:"
echo "   Ctrl+b, q, [number] - Jump to specific pane"
echo "   President: 0 | Technical: 1-7 | Business: 8-15"
echo ""
echo "📊 ENTERPRISE ORGANIZATIONAL STRUCTURE:"
echo ""
echo "   ┌─────────────┬─────────────┬─────────────┬─────────────┐"
echo "   │ President   │ Tech Boss   │ Sys Arch    │ Lead Dev    │"
echo "   │    (0)      │    (1)      │    (2)      │    (3)      │"
echo "   ├─────────────┼─────────────┼─────────────┼─────────────┤"
echo "   │ DevOps Eng  │ Security    │ Data Arch   │ Quality Eng │"
echo "   │    (4)      │    (5)      │    (6)      │    (7)      │"
echo "   ├─────────────┼─────────────┼─────────────┼─────────────┤"
echo "   │ Biz Boss    │ Strategy    │ Market      │ Finance     │"
echo "   │    (8)      │    (9)      │   (10)      │   (11)      │"
echo "   ├─────────────┼─────────────┼─────────────┼─────────────┤"
echo "   │ Operations  │ Product Mgr │ Customer    │ Compliance  │"
echo "   │   (12)      │   (13)      │   (14)      │   (15)      │"
echo "   └─────────────┴─────────────┴─────────────┴─────────────┘"
echo ""
echo "🔄 COORDINATION WORKFLOWS:"
echo ""
echo "📈 Hierarchical Analysis (ask_tree.sh):"
echo "   President → Technical Boss (1) → Technical Workers (2-7)"
echo "            → Business Boss (8) → Business Workers (9-15)"
echo ""
echo "📊 Flat Coordination (ask_flat.sh):"
echo "   President → All 15 Specialists (1-15) simultaneously"
echo ""
echo "📢 Broadcast Communication (ask_simple.sh):"
echo "   President → All panes including self (0-15)"
echo ""
echo "🎯 STRATEGIC FRAMEWORKS:"
echo ""
echo "🏗️  Technical Strategy Framework:"
echo "   • Architecture & Design: System design and scalability"
echo "   • Development & Quality: Code excellence and testing"
echo "   • Infrastructure & Security: Platform and protection"
echo "   • Data & Analytics: Information architecture"
echo ""
echo "💼 Business Strategy Framework:"
echo "   • Strategy & Planning: Vision and roadmap"
echo "   • Market & Finance: Opportunity and sustainability"
echo "   • Operations & Product: Execution and delivery"
echo "   • Customer & Compliance: Experience and governance"
echo ""
echo "📊 DECISION MAKING PROCESS:"
echo ""
echo "1️⃣  Information Gathering:"
echo "   • Technical feasibility assessment"
echo "   • Business viability analysis"
echo "   • Market opportunity evaluation"
echo "   • Risk and compliance review"
echo ""
echo "2️⃣  Cross-functional Analysis:"
echo "   • Technical-business alignment"
echo "   • Resource requirement assessment"
echo "   • Timeline and milestone planning"
echo "   • Success metrics definition"
echo ""
echo "3️⃣  Strategic Decision:"
echo "   • Go/No-go determination"
echo "   • Resource allocation decisions"
echo "   • Implementation strategy"
echo "   • Success measurement plan"
echo ""
echo "🎯 KEY DELIVERABLES:"
echo ""
echo "📋 Strategic Analysis:"
echo "   • Comprehensive feasibility assessment"
echo "   • Multi-dimensional risk evaluation"
echo "   • Resource and timeline planning"
echo "   • Success metrics and KPIs"
echo ""
echo "📊 Executive Summary:"
echo "   • Strategic recommendation"
echo "   • Implementation roadmap"
echo "   • Resource requirements"
echo "   • Risk mitigation plan"
echo ""
echo "🎛️  ANALYSIS DIMENSIONS:"
echo ""
echo "🔍 Technical Dimensions:"
echo "   • Feasibility: Can it be built?"
   • Scalability: Will it scale?"
echo "   • Security: Is it secure?"
echo "   • Maintainability: Can it be maintained?"
echo ""
echo "💡 Business Dimensions:"
echo "   • Viability: Is it profitable?"
echo "   • Market fit: Does market want it?"
echo "   • Competitive advantage: Does it differentiate?"
echo "   • Strategic alignment: Does it fit strategy?"
echo ""
echo "⚖️  Risk Dimensions:"
echo "   • Technical risks: Implementation challenges"
echo "   • Business risks: Market and financial risks"
echo "   • Operational risks: Execution challenges"
echo "   • Compliance risks: Regulatory requirements"
echo ""
echo "✅ Ready for enterprise-scale strategic coordination!"
echo "🎯 Awaiting complex strategic challenges..."
echo ""

# Log initialization
log_activity "gemini-squad-16" "President (Pane 0) initialized successfully" "INFO"